#!/usr/bin/env python3
"""Emit data/tiles/summer_catalog.gd from Warcraft II / Wargus summer tile indices.

The ripped sheet is 19 columns of 32x32 tiles with 1px gutters (stride 33).
Graphic index i maps to atlas cell (i % 19, i // 19), matching Wargus summer.lua.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "tiles" / "summer_catalog.gd"

COLS = 19
ROWS = 20

# Terrain ids must match scripts/run/elwynn_map.gd
T_GRASS = 0
T_COAST = 1
T_WATER = 2
T_FOREST = 3
T_ROCK = 4

# Wargus summer.lua graphic indices (into tilesets/summer/terrain/summer.png).
SOLID_WATER = [328, 329, 330, 331, 332, 333]
SOLID_COAST = [
    334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344,
    345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
    166,  # removed-rock (dirt patch)
]
SOLID_GRASS = [
    356, 357, 358, 359, 360, 361, 362, 363,
    364, 365, 366, 367, 368, 369, 370, 371,
    126,  # removed-tree (grass patch)
]
SOLID_FOREST = [125, 127, 128, 121, 122, 123]
SOLID_ROCK = [165, 177, 178, 179, 161, 162, 163]

# Mixed pairs: first type is the "filled" terrain for slot 0x00 (upper-left).
# Each pair has 14 slots (0x00 .. 0xD0) as listed in summer.lua.
MIXED_PAIRS: list[tuple[int, int, list[list[int]]]] = [
    # water / coast (shores). Slot bits = corners that are WATER.
    (
        T_WATER,
        T_COAST,
        [
            [206, 207],
            [208, 209],
            [210, 211, 212],
            [213, 214],
            [215, 216, 217],
            [218],
            [219, 220],
            [221, 222],
            [223],
            [224, 225, 226],
            [227, 228],
            [229, 230, 231],
            [232, 233],
            [234, 235],
        ],
    ),
    # rocks / coast. Slot bits = corners that are ROCK.
    (
        T_ROCK,
        T_COAST,
        [
            [150, 173],
            [142, 167],
            [164, 176],
            [147, 171],
            [149, 172],
            [154, 175],
            [151],
            [144, 169],
            [153, 174],
            [143, 168],
            [152],
            [146, 170],
            [148],
            [145],
        ],
    ),
    # coast / grass. Slot bits = corners that are COAST.
    (
        T_COAST,
        T_GRASS,
        [
            [270, 271],
            [272, 273],
            [274, 275, 276],
            [277, 278],
            [279, 280, 281],
            [282, 283],
            [284],
            [285, 286],
            [287, 288],
            [289, 290, 291],
            [292],
            [293, 294, 295],
            [296, 297],
            [298, 299],
        ],
    ),
    # forest / grass. Slot bits = corners that are FOREST.
    (
        T_FOREST,
        T_GRASS,
        [
            [129, 110],
            [102, 130],
            [124, 131],
            [107, 132],
            [133, 109],
            [139, 138],
            [111],
            [104, 136],
            [140, 141],
            [103, 135],
            [112],
            [106, 134],
            [137],
            [105],
        ],
    ),
]


def atlas(index: int) -> tuple[int, int]:
    return index % COLS, index // COLS


def fmt(pt: tuple[int, int]) -> str:
    return f"Vector2i({pt[0]}, {pt[1]})"


def emit_array(name: str, indices: list[int]) -> str:
    pts = [atlas(i) for i in indices]
    inner = ", ".join(fmt(p) for p in pts)
    return f"const {name}: Array[Vector2i] = [{inner}]"


def main() -> None:
    blocked: list[int] = []
    blocked.extend(SOLID_WATER)
    blocked.extend(SOLID_FOREST)
    blocked.extend(SOLID_ROCK)
    occupied: set[tuple[int, int]] = set()
    for i in SOLID_WATER + SOLID_COAST + SOLID_GRASS + SOLID_FOREST + SOLID_ROCK:
        occupied.add(atlas(i))

    lines: list[str] = [
        "class_name SummerCatalog",
        "extends RefCounted",
        "",
        "## Auto-generated by tools/catalog_summer_tiles.py — do not hand-edit.",
        "## Atlas: 32px tiles, 1px gutters, 19 columns. Indices from Wargus summer.lua.",
        "## Mixed slot 0..13 = Stratagus 0x00..0xD0. Bits 1..14 = which corners are type A:",
        "##   NW=1 NE=2 SW=4 SE=8. Slot table: 1→0, 2→1, 3→2, 4→3, 5→4, 6→5, 7→6,",
        "##   8→7, 9→8, 10→9, 11→10, 12→11, 13→12, 14→13.",
        "",
        f"const ATLAS_COLS := {COLS}",
        f"const ATLAS_ROWS := {ROWS}",
        "const TILE_SIZE := 32",
        "const ATLAS_SEPARATION := 1",
        "",
        "const T_GRASS := 0",
        "const T_COAST := 1",
        "const T_WATER := 2",
        "const T_FOREST := 3",
        "const T_ROCK := 4",
        "",
        emit_array("SOLID_GRASS", SOLID_GRASS),
        emit_array("SOLID_COAST", SOLID_COAST),
        emit_array("SOLID_WATER", SOLID_WATER),
        emit_array("SOLID_FOREST", SOLID_FOREST),
        emit_array("SOLID_ROCK", SOLID_ROCK),
        "",
        "const MIXED := {",
    ]

    for a, b, slots in MIXED_PAIRS:
        for slot_i, indices in enumerate(slots):
            pts = [atlas(i) for i in indices]
            for i in indices:
                occupied.add(atlas(i))
            if a in (T_FOREST, T_ROCK):
                blocked.extend(indices)
            inner = ", ".join(fmt(p) for p in pts)
            lines.append(f'\t"{a}_{b}_{slot_i}": [{inner}] as Array[Vector2i],')

    lines.append("}")
    lines.append("")

    # Deduplicate blocked while preserving order.
    seen_b: set[int] = set()
    blocked_unique: list[int] = []
    for i in blocked:
        if i not in seen_b:
            seen_b.add(i)
            blocked_unique.append(i)
    lines.append(emit_array("BLOCKED", blocked_unique))
    occ = sorted(occupied, key=lambda p: (p[1], p[0]))
    inner = ", ".join(fmt(p) for p in occ)
    lines.append(f"const OCCUPIED: Array[Vector2i] = [{inner}]")
    lines.append("")
    lines.append("const CORNER_SLOT := {")
    # bits 1..14 → slot 0..13
    for bits in range(1, 15):
        lines.append(f"\t{bits}: {bits - 1},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("static func solids_for(terrain: int) -> Array[Vector2i]:")
    lines.append("	match terrain:")
    lines.append("		T_GRASS:")
    lines.append("			return SOLID_GRASS")
    lines.append("		T_COAST:")
    lines.append("			return SOLID_COAST")
    lines.append("		T_WATER:")
    lines.append("			return SOLID_WATER")
    lines.append("		T_FOREST:")
    lines.append("			return SOLID_FOREST")
    lines.append("		T_ROCK:")
    lines.append("			return SOLID_ROCK")
    lines.append("		_:")
    lines.append("			return SOLID_GRASS")
    lines.append("")
    lines.append("")
    lines.append("static func mixed_for(type_a: int, type_b: int, slot: int) -> Array:")
    lines.append('	return MIXED.get("%d_%d_%d" % [type_a, type_b, slot], [])')
    lines.append("")
    lines.append("")
    lines.append("static func is_blocked_atlas(coords: Vector2i) -> bool:")
    lines.append("	return coords in BLOCKED")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(occ)} occupied, {len(blocked_unique)} blocked)")


if __name__ == "__main__":
    main()
